/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LisaaKuvaIkkuna.java
 *
 * Created on 25.10.2012, 14:28:00
 */
package kuvaarvoitusprojekti;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.channels.FileChannel;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import yhteydenhallinta.Tietovarasto;

/**
 *
 * @author s1000780
 */
public class LisaaKuvaIkkuna extends javax.swing.JFrame {

    private Tietovarasto varasto = new Tietovarasto();
    final JFileChooser fc = new JFileChooser();
    private File valittuTiedosto;

    /** Creates new form LisaaKuvaIkkuna */
    public LisaaKuvaIkkuna() {
        initComponents();
        fc.setMultiSelectionEnabled(false);
        fc.setAcceptAllFileFilterUsed(false);

        FileNameExtensionFilter filter = new FileNameExtensionFilter("Kuvat", "jpg", "jpeg", "gif", "png");
        fc.setFileFilter(filter);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lisaaNappi = new javax.swing.JButton();
        peruutaNappi = new javax.swing.JButton();
        polkuLaatikko = new java.awt.TextField();
        label1 = new java.awt.Label();
        haeNappi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        vihjeLaatikko1 = new javax.swing.JTextField();
        vihjeLaatikko3 = new javax.swing.JTextField();
        vihjeLaatikko4 = new javax.swing.JTextField();
        vihjeLaatikko2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        vastausLaatikko = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(kuvaarvoitusprojekti.KuvaArvoitusProjektiApp.class).getContext().getResourceMap(LisaaKuvaIkkuna.class);
        lisaaNappi.setText(resourceMap.getString("lisaaNappi.text")); // NOI18N
        lisaaNappi.setName("lisaaNappi"); // NOI18N
        lisaaNappi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lisaaNappiActionPerformed(evt);
            }
        });

        peruutaNappi.setText(resourceMap.getString("peruutaNappi.text")); // NOI18N
        peruutaNappi.setName("peruutaNappi"); // NOI18N
        peruutaNappi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peruutaNappiActionPerformed(evt);
            }
        });

        polkuLaatikko.setEditable(false);
        polkuLaatikko.setEnabled(false);
        polkuLaatikko.setName("polkuLaatikko"); // NOI18N
        polkuLaatikko.setText(resourceMap.getString("polkuLaatikko.text")); // NOI18N

        label1.setName("label1"); // NOI18N
        label1.setText(resourceMap.getString("label1.text")); // NOI18N

        haeNappi.setText(resourceMap.getString("haeNappi.text")); // NOI18N
        haeNappi.setName("haeNappi"); // NOI18N
        haeNappi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haeNappiActionPerformed(evt);
            }
        });

        jLabel1.setText(resourceMap.getString("Vihjeet.text")); // NOI18N
        jLabel1.setName("Vihjeet"); // NOI18N

        vihjeLaatikko1.setText(resourceMap.getString("vihjeLaatikko1.text")); // NOI18N
        vihjeLaatikko1.setName("vihjeLaatikko1"); // NOI18N

        vihjeLaatikko3.setText(resourceMap.getString("vihjeLaatikko3.text")); // NOI18N
        vihjeLaatikko3.setName("vihjeLaatikko3"); // NOI18N

        vihjeLaatikko4.setText(resourceMap.getString("vihjeLaatikko4.text")); // NOI18N
        vihjeLaatikko4.setName("vihjeLaatikko4"); // NOI18N

        vihjeLaatikko2.setText(resourceMap.getString("vihjeLaatikko2.text")); // NOI18N
        vihjeLaatikko2.setName("vihjeLaatikko2"); // NOI18N

        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        vastausLaatikko.setText(resourceMap.getString("vastausLaatikko.text")); // NOI18N
        vastausLaatikko.setName("vastausLaatikko"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(vihjeLaatikko1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                    .addComponent(polkuLaatikko, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                    .addComponent(lisaaNappi)
                                    .addComponent(vihjeLaatikko4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                    .addComponent(vihjeLaatikko3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                    .addComponent(label1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(haeNappi, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(peruutaNappi))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vihjeLaatikko2, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                        .addGap(91, 91, 91))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(294, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(vastausLaatikko, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                        .addGap(91, 91, 91))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lisaaNappi, peruutaNappi});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(haeNappi)
                            .addComponent(polkuLaatikko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vihjeLaatikko1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vihjeLaatikko2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vihjeLaatikko3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(vihjeLaatikko4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(vastausLaatikko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(peruutaNappi)
                            .addComponent(lisaaNappi)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void peruutaNappiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peruutaNappiActionPerformed
        this.dispose();
    }//GEN-LAST:event_peruutaNappiActionPerformed

    private void haeNappiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haeNappiActionPerformed

        int returnVal = fc.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            valittuTiedosto = fc.getSelectedFile();
            //This is where a real application would open the file.
            polkuLaatikko.setText(valittuTiedosto.getName());
        } else {
            System.out.println("Open command cancelled by user.");
        }
    }//GEN-LAST:event_haeNappiActionPerformed
private void copyFile(File sourceFile, File destFile) throws IOException {
        if (!destFile.exists()) {
            destFile.createNewFile();
        }

        FileChannel source = null;
        FileChannel destination = null;

        try {
            source = new FileInputStream(sourceFile).getChannel();
            destination = new FileOutputStream(destFile).getChannel();
            destination.transferFrom(source, 0, source.size());
        } finally {
            if (source != null) {
                source.close();
            }
            if (destination != null) {
                destination.close();
            }
        }
    }


    private void lisaaNappiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lisaaNappiActionPerformed
        if (polkuLaatikko.getText().isEmpty() || vihjeLaatikko1.getText().isEmpty()
                || vastausLaatikko.getText().isEmpty()) {
            return;
        }


        int kuvaid = varasto.haeKuvaMaara();
        String polku = polkuLaatikko.getText();
        String vihje1 = vihjeLaatikko1.getText();
        String vihje2 = vihjeLaatikko2.getText();
        String vihje3 = vihjeLaatikko3.getText();
        String vihje4 = vihjeLaatikko4.getText();
        String vastaus = vastausLaatikko.getText();

        List<String> vihjeet = new ArrayList<String>();
        if (!vihje1.isEmpty()) {
            vihjeet.add(vihje1);
        }
        if (!vihje2.isEmpty()) {
            vihjeet.add(vihje2);
        }
        if (!vihje3.isEmpty()) {
            vihjeet.add(vihje3);
        }
        if (!vihje4.isEmpty()) {
            vihjeet.add(vihje4);
        }

        Kuva k = new Kuva();
        k.setId(kuvaid);
        k.setPolku(polku);
        k.setVastaus(vastaus);
        k.setVihjeet(vihjeet);


        try {
            copyFile(valittuTiedosto, new File("kuvat\\" +  valittuTiedosto.getName()));
        } catch (IOException ex) {
            Logger.getLogger(LisaaKuvaIkkuna.class.getName()).log(Level.SEVERE, null, ex);
        }


        if
         (varasto.lisaaKuva(k)) {
            System.out.println(kuvaid);
            this.dispose();
        }
    }//GEN-LAST:event_lisaaNappiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new LisaaKuvaIkkuna().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton haeNappi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private java.awt.Label label1;
    private javax.swing.JButton lisaaNappi;
    private javax.swing.JButton peruutaNappi;
    private java.awt.TextField polkuLaatikko;
    private javax.swing.JTextField vastausLaatikko;
    private javax.swing.JTextField vihjeLaatikko1;
    private javax.swing.JTextField vihjeLaatikko2;
    private javax.swing.JTextField vihjeLaatikko3;
    private javax.swing.JTextField vihjeLaatikko4;
    // End of variables declaration//GEN-END:variables
}
